language: minimal
sudo: required

notifications:
  email: false

before_install:
  - git fetch --unshallow

jobs:
  include:
    - stage: build push
      script:
        - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` -t osirixfoundation/kheops-authorization:$TRAVIS_BRANCH .
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push osirixfoundation/kheops-authorization:$TRAVIS_BRANCH
    - stage: sonar
      script:
        - docker build -f sonarqube.Dockerfile -t sonarqube .
      after_success:
        - docker run --rm sonarqube gradle sonarqube "-Dsonar.organization=$SONAR_ORGANIZATION" "-Dsonar.branch.name=$TRAVIS_BRANCH" -Dsonar.projectKey=KheopsAuthorization -Dsonar.host.url=https://sonarcloud.io "-Dsonar.login=$SONAR_LOGIN" --no-daemon
